package com.redwasp.cubix;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.redwasp.cubix.FeedRecord;

import com.redwasp.cubix.FeedRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig feedRecordDaoConfig;

    private final FeedRecordDao feedRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        feedRecordDaoConfig = daoConfigMap.get(FeedRecordDao.class).clone();
        feedRecordDaoConfig.initIdentityScope(type);

        feedRecordDao = new FeedRecordDao(feedRecordDaoConfig, this);

        registerDao(FeedRecord.class, feedRecordDao);
    }
    
    public void clear() {
        feedRecordDaoConfig.clearIdentityScope();
    }

    public FeedRecordDao getFeedRecordDao() {
        return feedRecordDao;
    }

}
